### ISSUE TITLE
Windows usage

### ISSUE THREAD

**Issue by BaylorSci** [percolator/pout2mzid#6]
Hi, 
i'm trying to follow your instructions for Ubuntu, but installing on a windows (via visual studio and Cygwin) but having some issues, specifically during the make portion which returns the following: 

   5 | #include <boost/format.hpp>
  +++ |+#include <iostream>
    6 |
make[2]: *** [CMakeFiles/pout2mzid.dir/build.make:83: CMakeFiles/pout2mzid.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/pout2mzid.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

I am unsure if this is a windows specific issue, or is it just that this doesn't compile well on windows? Any advice would be welcome. I'm in the final stages of a manuscript preparation, where i would like to add the percolator output to my mzid files for quantification, and this is the only option i can find for doing this. 

Thanks in advance!!!

**Comment by BaylorSci** [comment]
Actually, never mind. I resolved this myself, by adding #include <iostream> to version_config.h and it compiled beautifully. Many thanks for this amazing package! Very much looking  forward to adding to our work.

**Comment by menzzana** [comment]
Hi

I am the developer of this tools and unfortunately I have only tested it on Linux, and there has not been that many requests for it on windows up until now. Good that you resolved it yourself as it was a long time ago I actually finished this, and I am glad that it is still being used and quite bug free., but as I have no windows to test it on at the time could you share exactly what you did to make it workable on Windows, so I can update this in the repo?

**Comment by percolator** [comment]
Hi,

We normally build our Windows installs through Visual Studio. I do not have
aunty recent experience with cygwin

Cheers
--Lukas

**Comment by BaylorSci** [comment]
The Cygwin installation was specifically for installation of items like the compiler library (specifically gcc) and cmake. Thereafter i followed the instructions outlined in the repository. When i ran the "make" component, i noticed the 1st comment error message, but once i added #include <iostream> to the version_config,h, the software compiled on windows. 

#New issue
However, in running through mzid samples generated using MS-GF+ using percolator (V3-05), the pout2mzid  line is returning "cannot read percolator out file XML path".  If i force it with -v, the script ends with 0 new values in the mzid file, which i know is incorrect since i have a venn diagram of overlap between percolator tsv output and the mzid file output. Any chance the schema has changed overtime and if so, how can i adjust this?

**Comment by percolator** [comment]
No, I do not think that the install procedure will run correctly under
cygwin, or at least we have not ever tried to make it run under cygwin.

cmake operates well with other compilers than gcc. Under windows we had
most success with Visual Studio's c++ compiler, however, I know very little
about the Windows environment.

--Lukas

**Comment by BaylorSci** [comment]
You are correct. After much faffing, it did not compile on windows. However, I got it to work on a linux virtual machine through the inclusion of <isostream> in the the version_config.h.in file.
